#pragma once
#include "meta_applied_enum.hpp"

namespace ssgc::frontend {
#define SSGC_AppliedEnum_eToken(m, sep, pre, lst) \
  pre m(kInvalid)                                  \
  sep m(kNone)                                     \
  sep m(kDirectiveInclude)                         \
  sep m(kDirectiveDefMacro)                        \
  sep m(kDirectiveEndmacro)                        \
  sep m(kDirectiveIf)                              \
  sep m(kDirectiveElse)                            \
  sep m(kDirectiveElif)                            \
  sep m(kDirectiveEndif)                           \
  sep m(kDirectiveIfdef)                           \
  sep m(kDirectiveIfndef)                          \
  sep m(kDirectiveUndef)                           \
  sep m(kKwDef)                                    \
  sep m(kKwFn)                                     \
  sep m(kKwClass)                                  \
  sep m(kKwMain)                                   \
  sep m(kKwImport)                                 \
  sep m(kKwNamespace)                              \
  sep m(kKwUse)                                    \
  sep m(kKwLib)                                    \
  sep m(kKwDll)                                    \
  sep m(kKwEnum)                                   \
  sep m(kKwIf)                                     \
  sep m(kKwElif)                                   \
  sep m(kKwElse)                                   \
  sep m(kKwCxif)                                   \
  sep m(kKwCxelif)                                 \
  sep m(kKwCxelse)                                 \
  sep m(kKwSwitch)                                 \
  sep m(kKwCase)                                   \
  sep m(kKwDefault)                                \
  sep m(kKwWhile)                                  \
  sep m(kKwFor)                                    \
  sep m(kKwReturn)                                 \
  sep m(kKwBreak)                                  \
  sep m(kKwContinue)                               \
  sep m(kKwInt)                                    \
  sep m(kKwUint)                                   \
  sep m(kKwReal)                                   \
  sep m(kKwBool)                                   \
  sep m(kKwChar)                                   \
  sep m(kKwByte)                                   \
  sep m(kKwCstr)                                   \
  sep m(kKwStr)                                    \
  sep m(kKwPtr)                                    \
  sep m(kKwList)                                   \
  sep m(kKwArray)                                  \
  sep m(kKwTrue)                                   \
  sep m(kKwFalse)                                  \
  sep m(kKwNone)                                   \
  sep m(kKwVoid)                                   \
  sep m(kKwIn)                                     \
  sep m(kKwAs)                                     \
  sep m(kKwCin)                                    \
  sep m(kKwCout)                                   \
  sep m(kKwNative)                                 \
  sep m(kKwConst)                                  \
  sep m(kKwRef)                                    \
  sep m(kKwPrivate)                                \
  sep m(kKwPublic)                                 \
  sep m(kKwStatic)                                 \
  sep m(kKwAny)                                    \
  sep m(kKwAuto)                                   \
  sep m(kKwType)                                   \
  sep m(kKwValue)                                  \
  sep m(kKwTemplate)                               \
  sep m(kKwProc)                                   \
  sep m(kHash)                                     \
  sep m(kAdd)                                      \
  sep m(kSub)                                      \
  sep m(kMul)                                      \
  sep m(kDiv)                                      \
  sep m(kMod)                                      \
  sep m(kAnd)                                      \
  sep m(kOr)                                       \
  sep m(kXor)                                      \
  sep m(kNot)                                      \
  sep m(kLsh)                                      \
  sep m(kRsh)                                      \
  sep m(kEq)                                       \
  sep m(kNeq)                                      \
  sep m(kLt)                                       \
  sep m(kGt)                                       \
  sep m(kLte)                                      \
  sep m(kGte)                                      \
  sep m(kSpaceship)                                \
  sep m(kAssign)                                   \
  sep m(kNewAssign)                                \
  sep m(kAddAssign)                                \
  sep m(kSubAssign)                                \
  sep m(kMulAssign)                                \
  sep m(kDivAssign)                                \
  sep m(kModAssign)                                \
  sep m(kAndAssign)                                \
  sep m(kOrAssign)                                 \
  sep m(kXorAssign)                                \
  sep m(kLshAssign)                                \
  sep m(kRshAssign)                                \
  sep m(kInc)                                      \
  sep m(kDec)                                      \
  sep m(kBnot)                                     \
  sep m(kBand)                                     \
  sep m(kBor)                                      \
  sep m(kLParen)                                   \
  sep m(kRParen)                                   \
  sep m(kLBrace)                                   \
  sep m(kRBrace)                                   \
  sep m(kLBracket)                                 \
  sep m(kRBracket)                                 \
  sep m(kSemicolon)                                \
  sep m(kColon)                                    \
  sep m(kComma)                                    \
  sep m(kPeriod)                                   \
  sep m(kDoubleColon)                              \
  sep m(kEllipsis)                                 \
  sep m(kCommercialAt)                             \
  sep m(kDollar)                                   \
  sep m(kBacklash)                                 \
  sep m(kQuestion)                                 \
  sep m(kLitInt)                                   \
  sep m(kLitUint)                                  \
  sep m(kLitBool)                                  \
  sep m(kLitChar)                                  \
  sep m(kLitByte)                                  \
  sep m(kLitCstr)                                  \
  sep m(kLitU1)                                    \
  sep m(kLitU8)                                    \
  sep m(kLitU16)                                   \
  sep m(kLitU32)                                   \
  sep m(kLitU64)                                   \
  sep m(kLitI8)                                    \
  sep m(kLitI16)                                   \
  sep m(kLitI32)                                   \
  sep m(kLitI64)                                   \
  sep m(kLitF32)                                   \
  sep m(kLitF64)                                   \
  sep m(kLitReal)                                  \
  sep m(kIdent)                                    \
  sep m(kWhitespace)                               \
  sep m(kNewline)                                  \
  sep m(kBlockComment)                             \
  sep m(kLineComment)                              \
  sep m(kEofile) lst

SSGC_MACRO_DefineEnumFromAppliedList(SSGC_AppliedEnum_eToken, eToken);

}  // namespace ssgc::frontend